name: Guestbook Actions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the guest'
        required: true
      email:
        description: 'Email of the guest'
        required: true
      message:
        description: 'Message from the guest'
        required: true

jobs:
  submit-message:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Submit Message
        run: |
          # Your implementation to submit the message using the MY_GITHUB_TOKEN
          # Example:
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ env.MY_GITHUB_TOKEN }}" \
              https://api.github.com/repos/yourusername/your-repo-name/dispatches \
              -d '{"event_type": "submit-message", "client_payload": {"name": "${{ github.event.inputs.name }}", "email": "${{ github.event.inputs.email }}", "message": "${{ github.event.inputs.message }}"}}'

  load-messages:
    runs-on: ubuntu-latest
    needs: [submit-message]
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Load Messages
        run: |
          # Your implementation to load messages using the MY_GITHUB_TOKEN
          # This is typically not needed as it would be handled by the frontend
          # However, if you want to log messages or perform some action after submission
          # You can use this step to interact with the GitHub API or another service
          echo "Loading messages..."
