name: Guestbook Actions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the guest'
        required: true
      email:
        description: 'Email of the guest'
        required: true
      message:
        description: 'Message from the guest'
        required: true

jobs:
  submit-message:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Submit Message
        run: |
          # Your implementation to submit the message using the MY_GITHUB_TOKEN
          # Example: Create an issue with the guest's information
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ env.MY_GITHUB_TOKEN }}" \
              https://api.github.com/repos/syx3204/message/issues \
              -d '{"title": "New Guestbook Message", "body": "Name: ${{ github.event.inputs.name }}\\nEmail: ${{ github.event.inputs.email }}\\nMessage: ${{ github.event.inputs.message }}" }'
