name: Post Message

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
      message:
        description: 'Message'
        required: true

jobs:
  post-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Save message
        run: |
          echo "${{ github.event.inputs.name }}: ${{ github.event.inputs.message }}" >> messages.txt
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add messages.txt
          git commit -m "Add new message" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
